// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	queries "github.com/eduardtungatarov/gofermart/internal/repository/balance/queries"
	mock "github.com/stretchr/testify/mock"
)

// BalanceRepository is an autogenerated mock type for the BalanceRepository type
type BalanceRepository struct {
	mock.Mock
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *BalanceRepository) FindByUserID(ctx context.Context, userID int) (queries.Balance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 queries.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (queries.Balance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) queries.Balance); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(queries.Balance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBalanceRepository creates a new instance of BalanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceRepository {
	mock := &BalanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
