// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"
)

type Withdrawal struct {
	ID          int32
	UserID      int
	OrderNumber string
	Sum         int
	ProcessedAt sql.NullTime
}
