// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"
)

type Querier interface {
	//FindByUserId
	//
	//  SELECT id, user_id, order_number, sum, processed_at FROM withdrawals
	//  WHERE user_id = $1
	//  ORDER BY processed_at desc
	FindByUserId(ctx context.Context, db DBTX, userID int) ([]Withdrawal, error)
}

var _ Querier = (*Queries)(nil)
