// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: balance.sql

package queries

import (
	"context"
)

const FindByUserId = `-- name: FindByUserId :one
SELECT id, user_id, current, withdrawn FROM balance
WHERE user_id = $1
`

// FindByUserId
//
//	SELECT id, user_id, current, withdrawn FROM balance
//	WHERE user_id = $1
func (q *Queries) FindByUserId(ctx context.Context, db DBTX, userID int) (Balance, error) {
	row := db.QueryRowContext(ctx, FindByUserId, userID)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Current,
		&i.Withdrawn,
	)
	return i, err
}
