// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"
)

type Querier interface {
	//SaveUser
	//
	//  INSERT INTO users (login, password, token)
	//  VALUES ($1, $2, $3)
	//  RETURNING id, login, password, token
	SaveUser(ctx context.Context, db DBTX, arg SaveUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
