// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package queries

import (
	"context"
)

const SaveUser = `-- name: SaveUser :one
INSERT INTO users (login, password, token)
VALUES ($1, $2, $3)
RETURNING id, login, password, token
`

type SaveUserParams struct {
	Login    string
	Password string
	Token    string
}

// SaveUser
//
//	INSERT INTO users (login, password, token)
//	VALUES ($1, $2, $3)
//	RETURNING id, login, password, token
func (q *Queries) SaveUser(ctx context.Context, db DBTX, arg SaveUserParams) (User, error) {
	row := db.QueryRowContext(ctx, SaveUser, arg.Login, arg.Password, arg.Token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Password,
		&i.Token,
	)
	return i, err
}
