// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	queries "github.com/eduardtungatarov/gofermart/internal/repository/withdrawal/queries"
)

// WithdrawalRepository is an autogenerated mock type for the WithdrawalRepository type
type WithdrawalRepository struct {
	mock.Mock
}

type WithdrawalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *WithdrawalRepository) EXPECT() *WithdrawalRepository_Expecter {
	return &WithdrawalRepository_Expecter{mock: &_m.Mock}
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *WithdrawalRepository) FindByUserID(ctx context.Context, userID int) ([]queries.Withdrawal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []queries.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]queries.Withdrawal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []queries.Withdrawal); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithdrawalRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type WithdrawalRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *WithdrawalRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *WithdrawalRepository_FindByUserID_Call {
	return &WithdrawalRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *WithdrawalRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID int)) *WithdrawalRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *WithdrawalRepository_FindByUserID_Call) Return(_a0 []queries.Withdrawal, _a1 error) *WithdrawalRepository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WithdrawalRepository_FindByUserID_Call) RunAndReturn(run func(context.Context, int) ([]queries.Withdrawal, error)) *WithdrawalRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// SaveWithdrawal provides a mock function with given fields: ctx, withdrawal
func (_m *WithdrawalRepository) SaveWithdrawal(ctx context.Context, withdrawal queries.Withdrawal) error {
	ret := _m.Called(ctx, withdrawal)

	if len(ret) == 0 {
		panic("no return value specified for SaveWithdrawal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.Withdrawal) error); ok {
		r0 = rf(ctx, withdrawal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithdrawalRepository_SaveWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWithdrawal'
type WithdrawalRepository_SaveWithdrawal_Call struct {
	*mock.Call
}

// SaveWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - withdrawal queries.Withdrawal
func (_e *WithdrawalRepository_Expecter) SaveWithdrawal(ctx interface{}, withdrawal interface{}) *WithdrawalRepository_SaveWithdrawal_Call {
	return &WithdrawalRepository_SaveWithdrawal_Call{Call: _e.mock.On("SaveWithdrawal", ctx, withdrawal)}
}

func (_c *WithdrawalRepository_SaveWithdrawal_Call) Run(run func(ctx context.Context, withdrawal queries.Withdrawal)) *WithdrawalRepository_SaveWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queries.Withdrawal))
	})
	return _c
}

func (_c *WithdrawalRepository_SaveWithdrawal_Call) Return(_a0 error) *WithdrawalRepository_SaveWithdrawal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WithdrawalRepository_SaveWithdrawal_Call) RunAndReturn(run func(context.Context, queries.Withdrawal) error) *WithdrawalRepository_SaveWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// NewWithdrawalRepository creates a new instance of WithdrawalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWithdrawalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WithdrawalRepository {
	mock := &WithdrawalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
