// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	queries "github.com/eduardtungatarov/gofermart/internal/repository/balance/queries"
)

// BalanceService is an autogenerated mock type for the BalanceService type
type BalanceService struct {
	mock.Mock
}

// GetUserBalance provides a mock function with given fields: ctx
func (_m *BalanceService) GetUserBalance(ctx context.Context) (queries.Balance, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBalance")
	}

	var r0 queries.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (queries.Balance, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) queries.Balance); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(queries.Balance)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBalanceService creates a new instance of BalanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceService {
	mock := &BalanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
