// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	queries "github.com/eduardtungatarov/gofermart/internal/repository/order/queries"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// GetUserOrders provides a mock function with given fields: ctx
func (_m *OrderService) GetUserOrders(ctx context.Context) ([]queries.Order, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOrders")
	}

	var r0 []queries.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]queries.Order, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []queries.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_GetUserOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserOrders'
type OrderService_GetUserOrders_Call struct {
	*mock.Call
}

// GetUserOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OrderService_Expecter) GetUserOrders(ctx interface{}) *OrderService_GetUserOrders_Call {
	return &OrderService_GetUserOrders_Call{Call: _e.mock.On("GetUserOrders", ctx)}
}

func (_c *OrderService_GetUserOrders_Call) Run(run func(ctx context.Context)) *OrderService_GetUserOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *OrderService_GetUserOrders_Call) Return(_a0 []queries.Order, _a1 error) *OrderService_GetUserOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_GetUserOrders_Call) RunAndReturn(run func(context.Context) ([]queries.Order, error)) *OrderService_GetUserOrders_Call {
	_c.Call.Return(run)
	return _c
}

// PostUserOrders provides a mock function with given fields: ctx, orderNumber
func (_m *OrderService) PostUserOrders(ctx context.Context, orderNumber string) error {
	ret := _m.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for PostUserOrders")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderService_PostUserOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostUserOrders'
type OrderService_PostUserOrders_Call struct {
	*mock.Call
}

// PostUserOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
func (_e *OrderService_Expecter) PostUserOrders(ctx interface{}, orderNumber interface{}) *OrderService_PostUserOrders_Call {
	return &OrderService_PostUserOrders_Call{Call: _e.mock.On("PostUserOrders", ctx, orderNumber)}
}

func (_c *OrderService_PostUserOrders_Call) Run(run func(ctx context.Context, orderNumber string)) *OrderService_PostUserOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_PostUserOrders_Call) Return(_a0 error) *OrderService_PostUserOrders_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_PostUserOrders_Call) RunAndReturn(run func(context.Context, string) error) *OrderService_PostUserOrders_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
