// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	queries "github.com/eduardtungatarov/gofermart/internal/repository/withdrawal/queries"
)

// WithdrawalService is an autogenerated mock type for the WithdrawalService type
type WithdrawalService struct {
	mock.Mock
}

type WithdrawalService_Expecter struct {
	mock *mock.Mock
}

func (_m *WithdrawalService) EXPECT() *WithdrawalService_Expecter {
	return &WithdrawalService_Expecter{mock: &_m.Mock}
}

// GetUserWithdrawals provides a mock function with given fields: ctx
func (_m *WithdrawalService) GetUserWithdrawals(ctx context.Context) ([]queries.Withdrawal, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWithdrawals")
	}

	var r0 []queries.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]queries.Withdrawal, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []queries.Withdrawal); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithdrawalService_GetUserWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserWithdrawals'
type WithdrawalService_GetUserWithdrawals_Call struct {
	*mock.Call
}

// GetUserWithdrawals is a helper method to define mock.On call
//   - ctx context.Context
func (_e *WithdrawalService_Expecter) GetUserWithdrawals(ctx interface{}) *WithdrawalService_GetUserWithdrawals_Call {
	return &WithdrawalService_GetUserWithdrawals_Call{Call: _e.mock.On("GetUserWithdrawals", ctx)}
}

func (_c *WithdrawalService_GetUserWithdrawals_Call) Run(run func(ctx context.Context)) *WithdrawalService_GetUserWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *WithdrawalService_GetUserWithdrawals_Call) Return(_a0 []queries.Withdrawal, _a1 error) *WithdrawalService_GetUserWithdrawals_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WithdrawalService_GetUserWithdrawals_Call) RunAndReturn(run func(context.Context) ([]queries.Withdrawal, error)) *WithdrawalService_GetUserWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// SaveWithdrawal provides a mock function with given fields: ctx, orderNumber, sum
func (_m *WithdrawalService) SaveWithdrawal(ctx context.Context, orderNumber string, sum int) error {
	ret := _m.Called(ctx, orderNumber, sum)

	if len(ret) == 0 {
		panic("no return value specified for SaveWithdrawal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, orderNumber, sum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithdrawalService_SaveWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWithdrawal'
type WithdrawalService_SaveWithdrawal_Call struct {
	*mock.Call
}

// SaveWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
//   - sum int
func (_e *WithdrawalService_Expecter) SaveWithdrawal(ctx interface{}, orderNumber interface{}, sum interface{}) *WithdrawalService_SaveWithdrawal_Call {
	return &WithdrawalService_SaveWithdrawal_Call{Call: _e.mock.On("SaveWithdrawal", ctx, orderNumber, sum)}
}

func (_c *WithdrawalService_SaveWithdrawal_Call) Run(run func(ctx context.Context, orderNumber string, sum int)) *WithdrawalService_SaveWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *WithdrawalService_SaveWithdrawal_Call) Return(_a0 error) *WithdrawalService_SaveWithdrawal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WithdrawalService_SaveWithdrawal_Call) RunAndReturn(run func(context.Context, string, int) error) *WithdrawalService_SaveWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// NewWithdrawalService creates a new instance of WithdrawalService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWithdrawalService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WithdrawalService {
	mock := &WithdrawalService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
