// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"
)

type Querier interface {
	//FindByUserId
	//
	//  SELECT id, user_id, order_number, status, accrual, uploaded_at FROM orders
	//  WHERE user_id = $1
	//  ORDER BY uploaded_at desc
	FindByUserId(ctx context.Context, db DBTX, userID int) ([]Order, error)
	//FindOrderByOrderNumber
	//
	//  SELECT id, user_id, order_number, status, accrual, uploaded_at FROM orders
	//  WHERE order_number = $1 LIMIT 1
	FindOrderByOrderNumber(ctx context.Context, db DBTX, orderNumber string) (Order, error)
	//SaveOrder
	//
	//  INSERT INTO orders (user_id, order_number, status, accrual)
	//  VALUES ($1, $2, $3, $4)
	//  RETURNING id, user_id, order_number, status, accrual, uploaded_at
	SaveOrder(ctx context.Context, db DBTX, arg SaveOrderParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
